Hometasks/hometask02
Frtn0717/conversion-magic pull request #1
Opened 2021-07-27 21:13 UTC by Frtn0717

Я так понял, что автоматически не может смержиться потому что я readme файл исправил отдельно в main и отдельно в hometasks? Это же не критично в данном случае? Но лучше так не делать, верно?

2021-07-29 06:56 UTC, ArtsiomFinenka requested changes

2021-07-29 06:56 UTC, ArtsiomFinenka commented on hometask02/coercion.js
> +str.addEventListener('click', function openCloseString(event) {
You use some ES6 features ( "const"), but don't use the arrow function as a callback. Let's use it here and below. And you shouldn't name the callback function here.

2021-07-29 06:56 UTC, ArtsiomFinenka commented on hometask02/coercion.js
> +        item.querySelector('.string_number_result').value = "'" + String(2021) + "'";
The same, let's use ES6 Template strings here and below.

2021-07-29 06:56 UTC, ArtsiomFinenka commented on hometask02/coercion.js
> +      }
IFor each case in the section "Type coercion for object":
- add the current value into HTML markup as "explanation". For example: 
![image](https://user-images.githubusercontent.com/47560539/127444028-1d5c8667-203d-4afb-8007-0b651ebb4208.png)
- to generate value use the real code (like in the previous sections). For example:
item.querySelector('.objects_boolean_result').value = `${true + false}`;
![image](https://user-images.githubusercontent.com/47560539/127444406-2a36052c-5472-47c8-8b90-cd5391af8606.png)

2021-07-29 06:56 UTC, ArtsiomFinenka commented on hometask02/index.html
> +        <label for="str_num_res"></label>
I see all labels are empty. Why do you use it? Please delete it in the whole file if label is empty

2021-07-29 06:56 UTC, ArtsiomFinenka commented on hometask02/coercion.js
> +const str = document.getElementById('string');
This comment is not related to this string.
I found a bug. Steps to reproduce:
- Click "Show result"
- Click on the "code" or previous "input" tag
![image](https://user-images.githubusercontent.com/47560539/127445619-c2e1ae03-f6f3-4a5d-81c6-e953504fe847.png)
- The input will be hidden, and the button will still have the value "Hide Result":
![image](https://user-images.githubusercontent.com/47560539/127445803-04df09e9-189c-4513-8557-ce8ac179f2ec.png)

2021-07-29 06:56 UTC, ArtsiomFinenka commented on hometask02/coercion.js
> +        item.setAttribute('disabled', 'disabled');
Why do you disable this in the JS code. It is better to disable in the HTML markup

2021-07-29 18:11 UTC, Frtn0717 commented on hometask02/index.html
> +        <label for="str_num_res"></label>
My bad. Just I thought if I use input then I need to use label for this input.

2021-08-04 06:36 UTC, ArtsiomFinenka approved these changes
You can merge it and resolve the conflict

2021-08-04 07:36 UTC, merged